Object.assign(pages, {
mike_bath_explore:{num:"P16",text:`I get up and start opening doors. The first one is a closet. The second one stops me cold.\n\nA man is asleep on the bed, completely naked. His cock is hard, thick, resting against his stomach. The sight hits me like a physical blow. I stand frozen in the doorway, staring, the wine (if I drank it) making the image burn brighter and harder to look away from.\n\n<em>I am staring at a stranger’s hard cock while wearing nothing but a thin tank and tiny shorts and I cannot make myself close the door.</em>`,
choices:[
{t:"I take a step forward, entranced, before I can stop myself.",next:"mike_brother"},
{t:"I force myself to close the door.",next:"mike_brother_close"}
]},

mike_brother:{num:"P17",text:`I take one step into the room before I can stop myself.\n\nThe air is warmer. I can see the slow rise and fall of his chest, the way his cock twitches slightly in sleep against his stomach — thick, heavy, unmistakably hard. My mouth is dry. The heat between my legs spikes so hard my knees feel unreliable. For a split second the only thought in my head is what it would feel like to touch it, to find out what this new body does with something like that in its hand or its mouth.\n\nMike’s voice cuts in from behind me before I can take another step. “Sorry — that’s my brother. Nasty habit of sleeping naked. Sorry you had to see that. Bathroom’s right down the hall.”\n\nI turn, face burning, and let him guide me the rest of the way. The image stays.`,
choices:[{t:"I go into the bathroom, the image of that cock still burned behind my eyes.",next:"mike_bathroom_cock"}]},

mike_brother_close:{num:"P18",text:`I close the door harder than I mean to.\n\nThe image is already burned in — the weight of him against his stomach, the slow pulse of a sleeping cock, the heat that spiked between my legs before I could stop it. My heart is trying to exit through my throat. Mike appears almost immediately, reading my face, apologetic and a little embarrassed on someone else’s behalf.\n\n“Sorry — that’s my brother. Nasty habit of sleeping naked. Sorry you had to see that. Bathroom’s right down the hall.”\n\nI nod. I do not trust my voice. My face is hot enough to hurt. I let him point me the right way and walk with my thighs pressed together, trying not to think about what I just almost stepped toward.`,
choices:[{t:"I go into the bathroom.",next:"mike_bathroom"}]},

mike_bathroom:{num:"P19",text:`I stand in front of the toilet, pull the short shorts down, and only then remember I have to sit. The cold porcelain against my bare thighs is a shock — the same cold I felt on the stairs or the hallway floor.\n\nAs I relieve myself it is oddly satisfying. I look down and see I am still glistening between my legs. I take a piece of toilet paper to wipe. The moment the paper touches my sensitive clit I flinch — in a good way.\n\nI stay there. Pressure. Slow circles. My free hand drifts up under the tank top; a nipple hardens under my fingers and begs to be pinched. Everything feels so good I forget where I am. I try to keep quiet. My legs start to spread. The pressure builds low and tight and perfect.\n\nI am almost there—\n\nKNOCK KNOCK KNOCK`,
choices:[{t:"I jolt up, yank the shorts back into place, heart hammering.",next:"mike_knock"}]},

mike_bathroom_cock:{num:"P20",text:`I stand in front of the toilet, pull the short shorts down, and only then remember I have to sit. The cold porcelain against my bare thighs is a shock.\n\nAs I relieve myself I can still see it — the hard cock on the bed, thick and heavy. The image will not leave. I look down and see I am still glistening. I take toilet paper to wipe. The moment it touches my clit I flinch hard.\n\nI stay there. Circles. Pressure. My free hand pinches a nipple through the thin tank. Every time I close my eyes I see that cock again. The dual sensation is filthy and perfect. My legs spread. I am so close I can taste it—\n\nKNOCK KNOCK KNOCK`,
choices:[{t:"I jolt up, yank the shorts back into place, the image still vivid.",next:"mike_knock"}]},

mike_knock:{num:"P21",text:`Mike’s voice through the door: “Hey Ana, I can’t find your key anywhere. I think I’m going to have to call a locksmith.”\n\nI exit the bathroom. My nipples are still hard and obvious through the tank top. I try to cover them with my arms and only succeed in pushing my breasts up and together. Mike’s eyes flick down for half a second. I pretend not to notice and walk back to the couch, mind still racing: how did this happen, why does it feel so good, why can’t I stop thinking about it.`,
choices:[{t:"I sit back down. He offers another drink while we wait.",next:"mike_wait"}]},

mike_wait:{num:"P22",text:`Mike sits on the other end of the couch, phone already out, scrolling for a locksmith. The apartment feels smaller than it did ten minutes ago. I can still feel the bathroom tile on the backs of my thighs, the almost-orgasm still coiled tight and unfinished between my legs.\n\n“Water? Coffee? More wine?”\n\nHis voice is casual. His eyes are not. They flick once to the hard points of my nipples under the thin tank and then away, as if he has decided not to notice. The air between us is thick enough to taste.`,
choices:[
{t:"Water. I need to stay clear.",next:"mike_tv"},
{t:"Coffee.",next:"mike_tv"},
{t:"More wine. The first glass already softened the edges.",next:"mike_movie"}
]},

mike_tv:{num:"P23",text:`He puts on a random daytime show. Something with a laugh track that does not match the room.\n\nWe sit in a silence that is not comfortable and not quite hostile. My body is still buzzing from the bathroom — from the almost, from the knock, from the way his eyes dropped when I tried to cover myself and only made it worse. Every small shift on the couch reminds me how wet I still am, how thin the shorts are, how close his hand is resting on the arm of the cushion between us.\n\nEventually his phone rings. The locksmith is downstairs at my door. The almost ends without resolving.`,
choices:[{t:"We go down to meet the locksmith.",next:"mike_locksmith"}]},

mike_movie:{num:"P24",text:`He pours another glass and puts on a movie he calls his favorite. He sits closer than before.\n\nEvery time something happens on screen he taps my thigh. “Look here.” The taps get more deliberate. Harder. Then he squeezes once, testing. Then his hand just rests there, warm and heavy on my bare skin.\n\nI freeze. I do not know what to do. I keep hoping the locksmith will call so this can end.\n\nA more romantic scene starts. His hand begins to move — slow strokes along my thigh, each one a little higher. The heat from the bathroom is still there, amplified by the wine. My breathing goes shallow. I watch his hand more than the movie. An inch from the edge of my shorts. My heartbeat is louder than the dialogue. I am biting my lip, entranced by the slow climb of his fingers, half hoping he will keep going and half terrified he will.\n\nHe pulls his hand away.\n\nHe’s on the phone. “Locksmith’s downstairs. He’s at your door. Let’s go fix this.”`,
choices:[{t:"We go down to meet the locksmith. My skin is still burning where his hand was.",next:"mike_locksmith"}]},

mike_locksmith:{num:"P25",text:`The locksmith is already at my door when we get downstairs — efficient, bored, the kind of man who has opened a hundred locked apartments and does not care what the occupants are wearing.\n\nHe opens it in under a minute. Mike is polite, apologetic, and does not push further in front of a stranger. He hands me a spare key he finally found in a different drawer and tells me to text if I need anything, the offer sitting in the air with more weight than the words. I thank him. The door closes. I am alone again in the apartment that is not mine, in a body that is not mine, still wet, still shaking, still tasting the almost of his hand on my thigh and the image I cannot unsee.`,
choices:[{t:"The second the door locks I am on the floor with my back against it.",next:"mike_home_orgasm"}]},

mike_home_orgasm:{num:"P26",text:`Shorts around my thighs. Two fingers buried. I come hard and silent, forehead pressed to my knees, the ghost of Mike’s hand still on my skin and (if I saw it) the image of his brother’s cock still burned behind my eyes. If I came from the continue-touching path, the memory of the older man’s eyes is still there too.\n\nAs the orgasm fades the tunnel vision goes with it.\n\nI actually see the apartment for the first time. Furniture. Photos on the wall. A laptop on the desk. A name on a piece of mail by the door.\n\nAna.\n\nThis body belongs to someone named Ana. I need to know who she is.`,
choices:[{t:"I look around, trying to understand whose life I am inside.",next:"system_normal"}]},

system_normal:{num:"P27",text:`The blue interface materializes with a soft digital chime.\n\nIts light paints my bare thighs, the rumpled shorts still hooked around my knees, the wet shine on my fingers. For a moment I can only stare — the same calm, bureaucratic glow that has been steering my body since the first orgasm. It does not care that I am still shaking. It does not care that the name on the mail by the door is Ana and the mind behind these eyes is not.\n\nIt has a quest. It always has a quest.`,
sys:`[QUEST AVAILABLE]\nCore Memory Package unlocked upon completion.\n\nRequirement:\nAchieve orgasm by rubbing your clit with one hand while sucking on two fingers of the other.\n\nReward:\n– Host identity data\n– Basic survival knowledge\n– Temporary reduction of disorientation\n\nFailure will result in escalating discomfort.`,
choices:[
{t:"I comply. One hand on my clit, two fingers in my mouth. (If I saw the brother’s cock, the memory floods back while I suck.)",next:"quest_cock"},
{t:"I comply cleanly. The dual sensation is intense but uncomplicated.",next:"quest_clean"}
]},

quest_cock:{num:"P28",text:`I follow the instructions. One hand circles my already swollen clit. The other rises to my mouth. Two fingers slide past my lips.\n\nEvery time I hollow my cheeks I see it again — hard, thick, resting against his stomach in the dim bedroom. The memory makes me suck harder, spit running down my wrist. The dual stimulation is overwhelming. My hips jerk. I come harder than the first time, moaning around my own fingers, the image of that cock still vivid behind my eyes as the orgasm rolls through me in long, shaking waves.`,
sys:`[QUEST COMPLETE]\nCore Memory Package delivered.\n\nIdentity: Ana, 25, graduate student / teaching assistant.\nLives alone. Best friend: Jessi.\nRecently ended a long-distance relationship.\nApartment layout, passwords, daily routines, and social contacts now accessible.\n\nSuccubi do not require conventional sleep or food in human quantities.\nSexual energy is primary sustenance.\nFurther quests will be issued according to host adaptation rate.`,
choices:[{t:"I absorb the memories. I know who this body belonged to. The path continues.",next:"apartment"}]},

quest_clean:{num:"P29",text:`I follow the instructions exactly.\n\nOne hand finds my clit — already swollen, already too sensitive — and begins slow circles. The other rises to my mouth. Two fingers slide past my lips. I taste myself, faint and musky, and the dual sensation is so strangely intimate that my eyes sting. My body responds as if it has been waiting for this precise combination. The climax arrives fast and clean: hips jerking, moan muffled around my own fingers, the blue window watching without comment as I shake apart on the floor of someone else’s apartment.`,
sys:`[QUEST COMPLETE]\nCore Memory Package delivered.\n\nIdentity: Ana, 25, graduate student / teaching assistant.\nLives alone. Best friend: Jessi.\nRecently ended a long-distance relationship.\nApartment layout, passwords, daily routines, and social contacts now accessible.\n\nSuccubi do not require conventional sleep or food in human quantities.\nSexual energy is primary sustenance.\nFurther quests will be issued according to host adaptation rate.`,
choices:[{t:"I absorb the memories. I know who this body belonged to. The path continues.",next:"apartment"}]},

body_hub:{num:"P30",text:`I am sitting on the edge of the bed in a body that is still brand new.\n\nThe pajama pants are pushed down around my thighs. The sleep shirt is somewhere on the floor. Cool air touches skin that has never been mine before — the soft weight of two small breasts, the completely smooth mound between my legs, the unfamiliar curve of hips and waist.\n\nI look down at myself and the reality of it hits again in a fresh wave. No cock. No familiar morning hardness. Just a delicate slit, already a little shiny, and the soft folds of outer lips that part when I shift my legs. My nipples are tight from the air and from pure nervous arousal. Every small movement makes the breasts bounce in a way that steals my breath.\n\n<em>This is my body now. These are my tits. That is my pussy. I am a girl and I can touch myself like one.</em>\n\nMy hands are shaking a little. I can do whatever I want. I can take my time. I can learn every new nerve ending before the dream — if it is a dream — ends.`,
choices:[
{t:"I cup my new breasts and play with the nipples — pinch, roll, pull, explore how sensitive they are.",next:"body_nipples"},
{t:"I spread my legs and explore the new folds between them with slow, curious fingers.",next:"body_folds"},
{t:"I push one finger, then two, inside myself and feel what it is like to be filled.",next:"body_finger"},
{t:"I roll onto my stomach and reach back to explore my own ass.",next:"body_ass"},
{t:"I put two fingers in my mouth and suck them while I touch myself — like I am performing for someone.",next:"body_mouth"},
{t:"I have explored enough. I want to come.",next:"body_cum"}
]},

body_nipples:{num:"P31",variants:[
`I lift both hands and cup the small soft breasts that should not be there.\n\nThe weight is real. Warm. When I squeeze gently the flesh yields under my palms in a way nothing on my old body ever did. I find the nipples with my thumbs and index fingers and roll them. They harden instantly, turning into tight little peaks that send sharp sparks straight down my spine and into the empty place between my legs.\n\nI pinch harder. Twist. Pull until the sensation borders on pain and then softens back into pure heat. A high, thin sound escapes my throat — a sound I have never made before. My hips shift on the mattress without permission. Looking down, I can see my own hands on girl-tits, my own fingers abusing the nipples of a body that used to be male only hours ago.\n\n<em>These are my nipples. I am pinching my own girl-nipples and it feels better than anything I ever did with my old body.</em>\n\nI keep going until both peaks are flushed dark pink and aching, and the wetness between my legs has soaked through to the sheets.`,
`I go back to my breasts because I cannot get enough of the novelty.\n\nThis time I push them together, watching the soft cleavage form between my palms. I lower my head and try to lick one of my own nipples. The angle is awkward but when my tongue finally drags across the tight peak the sensation is so sharp my thighs clamp shut. I suck on it, experimental, tasting clean skin and the faint salt of my own sweat, while my other hand keeps pinching and rolling the opposite nipple.\n\nEvery pull of my mouth sends another pulse of heat straight to my clit. I am a guy who just woke up as a girl, sitting on a stranger’s bed, sucking on my own tit like I have been waiting my whole life to do it.\n\nMaybe I have.`,
`Third time. I am shameless about it now.\n\nI lie back, arch my spine, and use both hands to abuse my nipples in slow, deliberate rhythms — pinch on the left while I stroke the right, then switch, then pull both at once until my back lifts off the mattress and a broken little moan spills out of me. The breasts are so sensitive that even the air moving across them after I let go feels like another touch.\n\nBetween my legs I am dripping. I have not even touched my pussy yet this round and I am already close. The transformation is still so fresh that every new sensation feels like the first time.`
],choices:[
{t:"I keep playing with my nipples — I need to feel more of this.",next:"body_nipples"},
{t:"I move my hands lower. I need to explore the rest.",next:"body_hub"},
{t:"I am close enough. I want to come.",next:"body_cum"}
]}
});
