var pages = {

title:{num:"P00",type:"title",html:`<div class="title"><h1>SUCCUBUS TAKEOVER</h1><p class="tag">First-person erotic transformation.<br>Every page has a unique ID (P01, P02…).<br>Tell me the number to fix anything.</p><div class="warn">18+ · Explicit · TG · First-person</div><br><button class="start" onclick="go('prologue')">Begin</button></div>`},

prologue:{num:"P01",text:`I have always been good at wanting things I never said out loud.\n\nI am twenty-seven. I live alone. Most nights the only light comes from the laptop. The thoughts arrive in the quiet between the last tab and sleep — soft, half-formed, never spoken.\n\nWhat it would feel like to be looked at the way I look at women. A body that invites instead of disappears under baggy clothes. Hands that look delicate. A voice that rises when surprised.\n\nOn the last ordinary night of my life the dream returns: the endless dim hallway of locked doors.\n\nTonight one door glows with soft pink light. The wood looks warm. The air in front of it smells faintly sweet and animal.`,
choices:[
{t:"I approach the glowing door and turn the knob. The wood is warm under my palm. I need to know what is on the other side.",next:"wake"},
{t:"I ignore the glow and try the ordinary locked doors again. I already know they will not open, but I try anyway.",next:"wake_forced"}
]},

wake_forced:{num:"P02",text:`I turn away from the pink light and push against a familiar cold metal door. It does not move. It has never moved.\n\nWhen I look back the glowing door is closer. The light is brighter. A soft, insistent pull starts behind my sternum, like a thread tied to something inside me and being gently reeled in.\n\nI take one step backward. The pull tightens. The door swings open on its own. Pink light flares, warm and almost liquid. A current seizes me — not pain, but absolute inevitability.\n\nThe door swallows me whole.`,
choices:[{t:"I fall through the light.",next:"wake"}]},

wake:{num:"P03",text:`My eyes open.\n\nSoft morning light filters through thin curtains. Unfamiliar ceiling. The air smells like clean laundry and something lightly floral. The pillow under my head is softer than the one I remember. The blanket feels lighter, almost silky against my skin.\n\nI try to sit up.\n\nThe first thing I notice is a slight, soft bounce against my chest. The fabric of a thin sleep shirt shifts with the movement. I look down.\n\nTwo small breasts push against the cloth. The outlines of my nipples are clearly visible, already starting to stiffen from the cooler air. The shirt is pale, slightly worn, and it clings in places it never would have on my old body.\n\nThen the second realization hits — the absence between my legs. There is no familiar weight. No morning hardness pressing against the sheets. Just a strange, open softness.\n\nMy hand shoots down almost in panic. My fingers meet only a soft, smooth mound and a delicate slit beneath thin pajama pants.\n\n<em>No way… no fucking way. These are tits. Those are actual tits on my chest. And between my legs… there’s nothing. Just a pussy. I have a pussy.</em>\n\nA wave of pure, disbelieving excitement crashes over me. My heart is already beating faster. It has to be a lucid dream. The most realistic one I have ever had.`,
choices:[
{t:"If this is a dream, I explore every sensation immediately. I need to feel everything before it ends.",next:"body_hub"},
{t:"This cannot be real. I throw the covers off, jump out of bed, and get out of this room. I need to prove the dream breaks when I leave.",next:"deny_leave"},
{t:"I freeze. I stare at the ceiling, then at the soft shapes on my chest. I touch nothing. I wait for it to end.",next:"freeze"}
]},

deny_leave:{num:"P04",text:`I refuse to accept it.\n\nI throw the covers off and scramble out of bed. The floor is cool under bare feet that are narrower than they should be. My heart is hammering so hard I can feel it in my throat and in the new soft weight on my chest. Whatever this is — dream, break, punishment — it ends when I leave the room. That is how dreams work. That is how they have always worked.\n\nI pull open the bedroom door, then the front door. The hallway is ordinary: fluorescent light, faint smell of someone else’s cooking, the low hum of the building. I step out in what I slept in before I can talk myself out of it, and the door swings shut behind me with a sound that is much too final.`,
choices:[{t:"I stand in the hallway, still trying to force myself awake.",next:"mike_hall"}]},

mike_hall:{num:"P05",text:`Two doors down, a man is locking his own door. He turns, sees me, and smiles like this is completely normal.\n\n“Hey Ana. Still in your pajamas I see, haha. Let me know when you’ve got my spare key back, yeah? Gotta run to the store.”\n\nHe waves and heads for the stairs. I freeze in place, the words landing wrong. Ana. He called me Ana.\n\nI look down.\n\nThin spaghetti-strap tank top, soft and loose, clinging where it shouldn’t. Short sleep shorts that barely cover anything. No bra. No underwear. Two small, bare breasts push against the thin fabric; nipples already tight from the hallway air. Between my legs there is nothing but smooth skin and the soft, open heat of a pussy. My ass fills the shorts in a way that feels exposed and wrong and electric.\n\nMy hands start moving before I decide to let them. Palm over one breast, then the other, feeling the soft weight. Fingers sliding under the waistband of the shorts, finding only slick folds and a swollen clit. Heat rises fast. Disbelief and arousal tangle together so tightly I cannot tell them apart.\n\n<em>These are my tits. This is my pussy. I am standing in a hallway half-naked and someone just called me Ana.</em>`,
choices:[
{t:"I pinch myself hard — arm, thigh, cheek — trying to force the dream to break.",next:"mike_panic"},
{t:"I keep touching. I cannot stop. The heat is too strong and I need to feel more of it.",next:"mike_touch_continue"}
]},

mike_panic:{num:"P06",text:`I dig my nails into the soft flesh of my upper arm hard enough to leave marks. I pinch my thigh. I slap my own cheek. Nothing breaks.\n\nThis is the school nightmare where you’re half-naked in the hallway and everyone can see, except the hallway is real and the body is real and the wetness on my fingers is real.\n\nI turn back to my door. It has closed and locked behind me. No key. No phone. No shoes. Only the thin pajamas and a body that keeps sending heat between my legs no matter how hard I try to ignore it.`,
choices:[{t:"I sink onto the cold marble stairs, arms wrapped around my knees.",next:"mike_stairs"}]},

mike_touch_continue:{num:"P07",text:`I do not stop.\n\nMy left hand stays under the tank top, cupping and squeezing one small breast, rolling the tight nipple between my fingers until sparks shoot down my spine. My right hand is deeper now, two fingers sliding through the slick folds, circling the swollen clit in slow, deliberate strokes. The wet sound is quiet but unmistakable in the empty hallway.\n\nMy hips rock forward against my own hand. A soft, broken sound escapes my throat. I bite my lip hard enough to taste metal and keep going. The shame is there — this is a public hallway, anyone could come up the stairs — but the heat is louder. My thighs are starting to shake. The short shorts are pushed aside enough that anyone looking would see exactly what I am doing.\n\n<em>I am standing in a hallway fingering myself in someone else’s body and I cannot make myself stop.</em>\n\nThe pressure builds. I lean my shoulder against the wall for balance, legs spreading a little wider, head tipping back. I am so close already that the edges of my vision are soft.`,
choices:[
{t:"I keep going. I am almost there. Just a little more.",next:"mike_touch_older"},
{t:"I force my hands away and try to pull myself together before someone sees.",next:"mike_panic"}
]},

mike_touch_older:{num:"P08",text:`I do not stop.\n\nTwo fingers buried, thumb pressing hard against my clit, other hand pinching a nipple through the thin tank. My breathing is high and short. A thin strand of wetness runs down the inside of my thigh. I am so close the hallway has narrowed to the wet sound of my own fingers and the pulse between my legs.\n\nFootsteps on the stairs below.\n\nI freeze mid-stroke, but it is already too late. An older man appears around the landing with a briefcase. His eyes land on me — shorts pushed aside, hand still between my legs, tank top rucked up enough to show the underside of one breast — and stay there for a long, terrible second.\n\nThe shame hits like ice water. My hands jerk free. I try to yank the shorts back into place and only succeed in making the fabric twist. My face burns so hard it hurts.`,
choices:[{t:"I drop to the floor, curling in on myself, unable to look at him.",next:"mike_touch_shame"}]},

mike_touch_shame:{num:"P09",text:`My knees hit the cold marble. I fold forward, arms wrapped tight around myself, forehead almost touching the floor. The wetness between my legs is still obvious. My nipples are still hard and visible through the tank. I can feel his eyes on the back of my neck.\n\nHe does not speak. After a moment that lasts forever, his footsteps continue past me and up the next flight of stairs. The sound of a door closing somewhere above is the only thing that tells me he is gone.\n\nI stay on the floor, shaking. The arousal has not fully left — it sits under the shame like a second pulse — but the shame is louder now. I want to disappear. I want the dream to end. Neither happens.\n\nA few minutes later, footsteps come up the stairs again. Different ones. Familiar.\n\nMike appears with a grocery bag. He stops when he sees me on the floor in the thin pajamas, face still flushed, shorts crooked.\n\n“Ana? What are you still doing here? Locked yourself out again, I see…”\n\nHe digs in his pocket, frowning, then softens. “Come on in. Let me find the key.”`,
choices:[{t:"I get up, still shaking, and follow him into his apartment.",next:"mike_return"}]},

mike_stairs:{num:"P10",text:`The stone is shocking against the backs of my bare thighs. I make myself as small as possible.\n\nThe heat between my legs does not fade. It throbs. I want to press my hand there, to scratch the itch, but an unexplainable shame keeps my arms locked around my knees. I spiral: how did this happen, why does it feel so good, what if someone else comes.\n\nFootsteps on the stairs below. An older man appears with a briefcase. His eyes land on my bare legs, the thin tank, the obvious lack of a bra, and linger a second too long. I make myself smaller, thighs pressed tight, arms crossed hard over my chest. He looks away and continues past without speaking.\n\nThe shame burns. Then the arousal returns stronger.`,
choices:[{t:"I wait, hoping the neighbor comes back.",next:"mike_return"}]},

mike_return:{num:"P11",text:`His name is Mike. I follow him into his apartment because I have nowhere else to go and because the alternative is the cold stairs and the memory of an older man’s eyes.\n\nThe place smells like soap, coffee, and something male that has nothing to do with the floral products in Ana’s bathroom. I stand just inside the door in the tiny pajamas, acutely aware that every shift of fabric makes my nipples drag against the tank and the shorts ride higher on my ass. If I came from the continue-touching path, my face is still hot and my thighs are still slick. If I came from the stairs, the cold marble is still on my skin. Either way, I am here, and he is looking for a key, and the morning is not finished with me.`,
choices:[{t:"I sit on his couch while he starts rummaging for the key.",next:"mike_couch"}]},

mike_couch:{num:"P12",text:`I sit. The couch is soft. My bare thighs press into the fabric and the short shorts ride higher.\n\nMike moves around the apartment opening drawers, checking a bowl by the door, muttering under his breath about where he left the spare. He glances over once and the glance catches on the thin tank top, on the obvious lack of a bra, on the way I am trying to sit with my knees together and failing.\n\n“You want coffee? Tea? Wine, haha?”\n\nThe question is meant to be light. The air in the room is not. My nipples are still hard. The heat between my legs has not gone away since the hallway. I can still feel the cold marble of the stairs — or the floor, depending on which path brought me here — on my skin like a memory of exposure.`,
choices:[
{t:"Coffee. Something normal.",next:"mike_drink_neutral"},
{t:"Tea. Something warm and safe.",next:"mike_drink_neutral"},
{t:"Wine. I need something to take the edge off this nightmare.",next:"mike_drink_wine"}
]},

mike_drink_neutral:{num:"P13",text:`He brings the mug and sets it on the table within my reach. Coffee. Ordinary. The heat of it against my palms is almost grounding — a small normal object in a morning that has refused to be normal since I opened my eyes.\n\nI drink. It does nothing to the low throb between my legs or the way my nipples keep catching on the inside of the tank top every time I breathe. Mike moves through the apartment opening drawers, muttering. The search is taking too long.\n\nThen the other pressure arrives: sudden, insistent, low in my belly. I need to pee. The realization comes with a fresh wave of vulnerability — this body, these thin clothes, his bathroom.`,
choices:[
{t:"I ask him where the bathroom is.",next:"mike_bath_ask"},
{t:"I get up and try to find it myself.",next:"mike_bath_explore"}
]},

mike_drink_wine:{num:"P14",text:`He pours a glass from a bottle on the counter and hands it to me without ceremony.\n\nThe wine is cheap and a little sweet. It hits the back of my throat and spreads warm through my chest, and almost immediately the sharp edges of the panic soften. The heat between my legs feels less like a problem I need to solve and more like something I could lean into if I stopped fighting. Mike goes back to searching. I sit on his couch in thin pajamas with a glass of wine in a stranger’s apartment and try to remember how I got here.\n\nWhile he keeps opening drawers I realize I need to pee. Badly. The pressure is sudden and insistent. The wine makes everything feel a little slower, a little heavier, a little more open to whatever happens next.`,
choices:[
{t:"I ask him where the bathroom is.",next:"mike_bath_ask"},
{t:"I get up and try to find it myself. The wine makes me less careful.",next:"mike_bath_explore"}
]},

mike_bath_ask:{num:"P15",text:`“Bathroom?” I ask. My voice still sounds wrong in my own ears — higher, softer, the ghost of Ana’s register sitting on top of whatever is left of Ethan’s.\n\nMike points down the short hallway without hesitation. “Second door on the left. Clean towels on the shelf if you need.”\n\nI walk there on legs that do not feel entirely steady. The bathroom is a typical guy bathroom: dark towels, cheap body wash, a razor on the sink, the faint smell of aftershave that has nothing to do with the floral products in Ana’s apartment. Ordinary. Almost comforting. A small island of male space in a morning that has been nothing but the opposite.`,
choices:[{t:"I close the door and face the toilet.",next:"mike_bathroom"}]}
};
