Object.assign(pages, {
body_folds:{num:"P32",variants:[
`I push the pajama pants the rest of the way off and spread my legs.\n\nFor a long moment I just look. Completely smooth. No hair. The outer lips are soft and already a little parted, shiny with wetness that has nothing to do with the dream logic and everything to do with how hard I have been staring at my own new body. I reach down with two fingers and carefully open myself.\n\nThe air hits the inner folds and I shiver hard. Pink. Delicate. Unfamiliar. I stroke up and down, gathering slickness, mapping the new landscape. When my fingertip finds the small swollen nub at the top — my clit — the jolt is so strong my hips jerk and a broken sound tears out of my throat.\n\n<em>That is my clit. I am rubbing my own clit with my own fingers and it feels like every nerve in my body just lit up at once.</em>\n\nI circle it slowly, then faster, then slow again, learning the difference between too much and perfect. My free hand finds a nipple and pinches in time with the strokes. The dual sensation makes my toes curl.`,
`I return to the soft wet heat between my legs because the first exploration was not enough.\n\nThis time I take longer. I spread the outer lips with one hand and use the fingertips of the other to trace every fold, every ridge, the entrance that flutters when I brush it. I gather wetness and paint it up over my clit in lazy circles until my thighs start to shake. Looking down I can see my own fingers working a pussy that did not exist this morning — shiny, swollen, unmistakably aroused.\n\nI used to jerk off thinking about bodies like this. Now I am inside one, touching it from the outside, and the feedback loop of sight and sensation is almost too much. A thin strand of wetness stretches between my fingers when I lift them. I am soaked.`,
`Third pass. I am less careful, more greedy.\n\nI plant my feet on the mattress, knees wide, and rub my clit with the flat of two fingers in firm, steady strokes while I watch everything in the mirror across the room if I angle myself right — or simply stare down at the pink swollen flesh under my own hand. Every circle winds the pressure tighter. My free hand is fisted in the sheets. My breathing has gone high and short.\n\nI am a newly made girl edging herself on a bed that still smells like someone else’s detergent, and the only thought left in my head is how good it feels to finally have a body that answers like this.`
],choices:[
{t:"I keep rubbing my clit, edging myself, learning every sensation.",next:"body_folds"},
{t:"I push a finger inside myself.",next:"body_finger"},
{t:"Back to the other options. I want to try something else.",next:"body_hub"},
{t:"I am ready to come.",next:"body_cum"}
]},

body_finger:{num:"P33",variants:[
`I slide one finger into the tight, slick heat.\n\nThe walls clench around the intrusion immediately — warm, velvety, alive in a way my old body never was. The stretch is small but the sensation is enormous. I add a second finger. The burn of it makes me moan out loud. I curl them, searching, and find a spot on the front wall that makes my whole body jolt like I have been shocked.\n\n<em>I am fingering my own pussy. I am a guy who woke up as a girl and I am knuckle-deep in myself and it feels better than every orgasm I ever had as a man.</em>\n\nI thrust deeper, faster. The wet sounds are obscene in the quiet room. My other hand goes to a nipple and pinches hard in time with every push. My hips lift to meet my own fingers. I can feel myself getting closer with every stroke.`,
`I push back inside because the first time was only a taste.\n\nThree fingers this time. The stretch burns in the best way. I can feel every ridge of my own walls gripping and releasing. When I press up against that sensitive spot the pleasure radiates out through my hips and down my thighs until my legs are shaking. Looking down I watch my own fingers disappear into a body that still feels borrowed and completely mine at the same time.\n\nI used to wonder what it would feel like to be fucked. This is the closest I have ever been — my own hand, my own pace, my own tight heat closing around the intrusion like it was made for this.`,
`I am past careful.\n\nI fuck myself with short, hard strokes, the heel of my palm grinding against my clit on every inward thrust. The dual pressure is devastating. My free hand is locked on one breast, kneading, pinching, pulling. Sweat has started along my hairline. The sheets under me are a mess. Every time I bottom out I make a sound I do not recognize as my own voice — higher, needier, completely given over to the new nerves.\n\nI could come like this in another ten seconds if I let myself.`
],choices:[
{t:"I keep fingering myself, chasing the feeling deeper.",next:"body_finger"},
{t:"I add my other hand on my clit at the same time.",next:"body_both"},
{t:"Back to other options.",next:"body_hub"},
{t:"I come on my fingers.",next:"body_cum"}
]},

body_both:{num:"P34",variants:[
`One hand working between my legs — two fingers buried deep, curling against that perfect spot — the other rubbing tight circles on my swollen clit.\n\nThe dual sensation is overwhelming. My thighs shake. My voice breaks into high, broken sounds I have never made in my life. I am not going to last long like this. The pressure builds in tight rising waves until the edges of my vision go soft and the only thing left is the wet sound of my own hands and the desperate rock of my hips.\n\n<em>I am a newly transformed girl finger-fucking herself and rubbing her own clit and it is the best thing I have ever felt.</em>`,
`I go back to both hands because nothing else comes close.\n\nFingers inside. Clit under my other hand. I set a rhythm — thrust, circle, thrust, circle — until my whole body is moving with it. Sweat runs between my small breasts. My free toes curl hard into the sheets. Every time I hit the right angle on both points at once a bright white spark shoots up my spine.\n\nI am edging myself on purpose now, backing off just enough to keep from tipping over, then diving back in. The control is intoxicating. The new body answers every single touch.`
],choices:[
{t:"I edge myself one more time — not yet.",next:"body_hub"},
{t:"I let go and come.",next:"body_cum"}
]},

body_ass:{num:"P35",variants:[
`I roll onto my stomach, push the pants the rest of the way down, and reach back.\n\nThe curve of my own ass is soft under my palm — fuller than anything I used to have, yielding when I squeeze. I spread myself open with both hands and feel the cool air on places that have never been this exposed to me before. When I press a single fingertip against the tight rear entrance it flutters. A different, darker heat blooms low in my belly.\n\n<em>I am touching my own ass and it is turning me on. I am a guy who just became a girl and I am exploring every hole I now have.</em>\n\nI wet the fingertip in my mouth and return it. The tight ring of muscle resists, then yields just enough to let the tip inside. The sensation is strange and intense and immediately addictive. My free hand finds my clit almost automatically. The combination makes me whimper into the pillow.`,
`I go back because the first careful touch was not enough.\n\nThis time I take longer. I spread myself wider, look over my shoulder if I can manage the angle, and work the tip of one finger in slow circles around the rim until the muscle softens. When I push in to the first knuckle the fullness is small but the awareness of it is huge. At the same time I rub my clit in matching circles. The two sensations braid together until I am rocking back onto my own hand, chasing more.\n\nI used to be the one who did the touching. Now I am the one being opened, even if the hand doing it is still mine.`,
`Third time. Greedier.\n\nI get two fingertips slick with my own wetness from between my legs and press them against the tight entrance until it gives. The stretch burns. I push deeper, slow, while my other hand works my clit without mercy. Face down, ass up, newly made girl-body taking my own fingers in both places — the image of it alone is almost enough to push me over.`
],choices:[
{t:"I keep exploring, slow and curious.",next:"body_ass"},
{t:"I go back to my front instead.",next:"body_hub"},
{t:"I want to come while touching myself like this.",next:"body_cum"}
]},

body_mouth:{num:"P36",variants:[
`I push two fingers into my mouth and suck them while my other hand works between my legs.\n\nThe dual stimulation is filthy and effective. The wet sounds of my mouth and the wet sounds of my pussy mix in the quiet room. My hips rock against my hand. My tongue curls around my own fingers like they belong to someone else. I hollow my cheeks and suck harder every time I circle my clit, turning the whole thing into a feedback loop of sight, sound, and sensation.\n\n<em>I am performing for an audience of one and it is working. I am a newly transformed girl sucking on my own fingers and fingering myself and I have never been this turned on in my life.</em>`,
`I return to the combination because it makes me feel used in the best way.\n\nThis time I make it filthier. I get my fingers dripping from between my legs first, then push them into my mouth so I can taste myself — musky, slightly sweet, completely unfamiliar. While I suck them clean I go back to rubbing my clit with the other hand. The taste and the touch together make my eyes flutter shut. I am learning what I taste like. I am learning what I sound like when I moan around my own fingers.\n\nEvery version of Ethan who ever jerked off to the idea of being a girl is getting exactly what he wanted.`,
`I am past shy.\n\nI fuck my mouth with three fingers while I fuck my pussy with the other hand, matching the rhythm, letting spit run down my wrist and wetness run down my thighs. The room smells like sex. My reflection in the dark window is a flushed, open-mouthed girl with her hands busy and her new body completely given over to the exploration. I could come from the image alone.`
],choices:[
{t:"I keep sucking and rubbing, lost in it.",next:"body_mouth"},
{t:"I switch to a different focus.",next:"body_hub"},
{t:"I come with my fingers in my mouth.",next:"body_cum"}
]},

body_cum:{num:"P37",text:`I stop holding back.\n\nThe orgasm rips through me in long, rolling waves that start deep in my core and radiate out through every new nerve ending I have spent the last however-long discovering. My pussy clamps down hard around nothing — or around my fingers if they are still inside — pulsing in strong rhythmic squeezes I can feel all the way up into my belly. My back arches off the bed. A broken, high-pitched moan fills the room and keeps going until my throat is raw.\n\nWhen it finally eases I collapse, chest heaving, small breasts rising and falling fast, thighs trembling, fingers still coated and buried or resting wet against my swollen clit. The sheets under me are a mess. My whole body feels oversensitive and liquid and still faintly hungry.\n\n<em>I finally got to experience it. Even if this is just a dream… it was worth it. Every second of it.</em>\n\nI close my eyes, still breathing hard, waiting to wake up in my old body, in my old bed, with the familiar weight between my legs.\n\nA few seconds pass.\n\nA cool breeze drifts in through the open window. My still-sensitive nipples harden again under the air. The absence between my legs remains absolute.\n\nMy eyes snap open.\n\n<em>Why am I not waking up…?</em>\n\nA translucent blue window materializes in the air above me with a soft digital chime.`,
sys:`[SYSTEM INITIALIZING]\nOrgasm achieved.\nSuccubus UI is now operational.`,
choices:[{t:"I stare at the floating window.",next:"system_normal"}]},
freeze:{num:"P38",text:`I lie perfectly still.\n\nThe cool air from the open window moves across my skin and makes the nipples under the thin shirt tighten until they are clearly visible and sensitive enough that even the fabric shifting with my breathing is almost too much. A low, unfamiliar ache begins between my legs — not pain, not exactly desire, something in between that has no name in the body I used to have.\n\nI stare at the ceiling. I wait for the dream to end. The ceiling does not change. The ache deepens. Eventually the need to know what this body can feel becomes stronger than the fear of finding out.`,
choices:[{t:"Slowly, carefully, I begin to explore.",next:"body_hub"}]},

apartment:{num:"P39",text:`The memories settle like sediment in water.\n\nI am Ana. Twenty-five. Graduate student. Teaching assistant. Jessi texts almost every day and has for years. I used to swim three times a week. I ended a long-distance relationship a few weeks ago and have been quietly, carefully lonely ever since — the kind of loneliness that makes a person leave a door ajar without admitting they are hoping someone will walk through it.\n\nI walk the apartment with new eyes. Bathroom full of lotions and a curling iron and a half-empty pack of birth-control pills that the System has already noted as unnecessary. The bed still smells like the first morning. The name on the mail by the door is mine and is not.`,
sys:`[INFORMATIONAL]\nSuccubi do not require hormonal contraception.\nHost systems already adjusted for energy absorption.`,
choices:[
{t:"I open the closet and examine Ana’s clothes.",next:"clothes"},
{t:"I sit down and research ‘succubus’ and ‘body swap’ online first.",next:"research"}
]},

research:{num:"P40",text:`I find Ana’s laptop on the desk. The password rises out of the new memories without effort — a birthday, a pet name, the kind of thing a person uses when they do not expect their life to be stolen.\n\nSearch results are a mess of folklore, erotica, and occult forums that treat succubi as metaphor or as masturbation fuel. Buried in the noise I find one useful fragment repeated across different threads: some accounts claim a newly awakened host can, under rare conditions, influence the System itself if enough voluntary essence is absorbed quickly and directed inward instead of outward. A seed of a different path. I close the laptop before the forums can tell me how many people broke themselves trying.`,
choices:[{t:"I close the laptop and face the closet.",next:"clothes"}]},

clothes:{num:"P41",text:`The closet is full of soft fabrics and cuts designed for a body that invites looking.\n\nWhen I reach for a pair of dark jeans that might have passed as unisex, a mild static shock runs across my fingertips — the System’s quiet refusal. Masculine clothing is restricted. The message is clear without words.\n\nI stand in front of the open doors and look at what remains. Practical pieces that will still cling. Cute pieces that will still show the shape of my breasts. And the ones that leave almost nothing to the imagination — the ones Ethan used to imagine in the dark and never thought he would have to put on his own skin.`,
choices:[
{t:"I accept a normal outfit and the way it makes me feel.",next:"cafe"},
{t:"I hate every second of it, but wear something modest because the alternative is worse.",next:"cafe"},
{t:"I pick the sluttiest combination in the closet and lean into it hard. This was my wish. I am going to use it.",next:"clothes_slut"}
]}
});
